package ru.alishev.springcourse.models;

/**
 * @author Neil Alishev
 */

import javax.validation.constraints.*;

/** это человек у человека есть id уникальный идентификатор   */
public class Person {
    private int id;
    /** у человека есть имя */
    /**@ аннотациями устанавливаем валидацию полей */
    @NotEmpty(message = "Name should not be empty")
    @Size(min =2, max = 30, message = "Name should be between 2 and 30 characters")
    private String name;

    @Min(value = 0, message = "Age should be greater than 0")
    private int age;

    @NotEmpty(message = "Email should not be empty")
    @Email ( message = "Email should be valid" )
    private String email;

    /** Страна, название города, почтовый индекс (6-ть цифр) */
    /** сайт форматов регулярных выражений http://rexegg.com/regex-quickstart.html */
    /** Russian, Moscow, 123456 */
    @Pattern(regexp = "[A-Z]\\w+, [A-Z]\\w+, \\d{6}", message = "Your address should be in this format: Russian, Moscow, 123456")
    private String address;

    /** создаем пустой конструктор */
    public Person () {
    }
/**
    create table  Person
    (
            id    int generated by default as identity primary key,
            name  varchar not null,
            age   int check (age > 0),
            email varchar UNIQUE
    );

    -- добавляем колонку адресс
    alter table person add column address varchar not null;
*/
    public Person(int id, String name, int age, String email, String address) {
        this.id         = id;
        this.name       = name;
        this.age        = age;
        this.email      = email;
        this.address    = address;
    }

    /** создаем конструктор */
    public Person(int id, String name) {
        this.id = id;
        this.name = name;
    }

    /** сгенерированы геттеры и сеттеры */
    public int getId() {
        return id;
    }

    /** сгенерированы геттеры и сеттеры */
    public void setId(int id) {
        this.id = id;
    }

    /** сгенерированы геттеры и сеттеры */
    public String getName() {
        return name;
    }

    /** сгенерированы геттеры и сеттеры */
    public void setName(String name) {
        this.name = name;
    }

    /** сгенерированы геттеры и сеттеры */
    public int getAge() {
        return age;
    }

    /** сгенерированы геттеры и сеттеры */
    public void setAge(int age) {
        this.age = age;
    }

    /** сгенерированы геттеры и сеттеры */
    public String getEmail() {
        return email;
    }

    /** сгенерированы геттеры и сеттеры */
    public String getAddress() {
        return address;
    }

    /** сгенерированы геттеры и сеттеры */
    public void setAddress(String address) {
        this.address = address;
    }

    /** сгенерированы геттеры и сеттеры */
    public void setEmail(String email) {
        this.email = email;
    }
}
